### PR TITLE
Update OpenCV to only buffer image for up to 1 second to fix "refresh image" button in calibrator

### PR DESCRIPTION
**Pull request by blakegong**
😄 Please check the commit message for detailed description 🙏

### CODE REVIEW

**Comment by blakegong** [comment]
Wait I realised the first commit has been fixed by #21, in a different way, alamah! Hold on

**Comment by blakegong** [comment]
@alex-ong ready for review 🙏

**Review by timotheeg — APPROVED** [review]
:+1: lgtm

**Comment by alex-ong** [comment]
OpenCV is different to File right?

**Comment by alex-ong** [comment]
Ok cool looks good; i think 1 second is a bit weird of a magic time; 
Does this ensure you get the latest frame in the configurator? Maybe we could change api to choose between buffered (dont drop frames) and latest

**Comment by blakegong** [comment]
Haha yeah 1 second is a magic number. It's because OpenCV capture were actually written in a slightly different way than others.

All the other capturing method doesn't do any buffering right now.

I think if one day you think capturing source buffering is needed, and have a universal way to do it, then we just do it, including changing this magic number. Before that, having this magic number on OpenCV only should be fine.

**Pull request merged**
